### ISSUE TITLE
Some Error While Trying To Dry Run It.

### ISSUE THREAD

**Issue by Abhineel-Nandi** [AtoraSuunva/Booru-Discord#39]

**Comment by AtoraSuunva** [comment]
Try running `node ./src/Sleet.js`

**Comment by Abhineel-Nandi** [comment]
Thanks a lot for your help.
By the way can you help me in setting up the database for this I really don't have a good knowledge of setting up these.
I have installed psql after that can you guide me on what should I do next. Thanks  for any help in advance .

**Comment by Abhineel-Nandi** [comment]
I have made a dotenv file for storing the credentials i dont know on how to create an schema and table, all those things . Could you help in how to make those using pgAdmin.
For Now I am getting this error
`   
Error: Logger Caught
ID: 13c66
Uncaught Promise Error: 
error: relation "booru_settings" does not exist
Stack:
error: relation "booru_settings" does not exist
    at Parser.parseErrorMessage (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\index.js:8:42)
    at Socket.emit (events.js:322:22)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Promise:
Promise {
  <rejected> error: relation "booru_settings" does not exist
      at Parser.parseErrorMessage (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
      at Parser.handlePacket (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\index.js:8:42)
      at Socket.emit (events.js:322:22)
      at Socket.EventEmitter.emit (domain.js:482:12)
      at addChunk (_stream_readable.js:286:12)
      at readableAddChunk (_stream_readable.js:268:9)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '15',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c',
    line: '1379',
    routine: 'parserOpenTable',
    _length: 176,
    stackframes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
}
`

**Comment by Abhineel-Nandi** [comment]
I am getting this error after creating an dotenv file and setting the evnironment tables:
"
Error: Logger Caught
ID: 13c66
Uncaught Promise Error: 
error: relation "booru_settings" does not exist
Stack:
error: relation "booru_settings" does not exist
    at Parser.parseErrorMessage (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\index.js:8:42)
    at Socket.emit (events.js:322:22)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Promise:
Promise {
  <rejected> error: relation "booru_settings" does not exist
      at Parser.parseErrorMessage (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
      at Parser.handlePacket (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (E:\User\github-bot\Booru-Discord\node_modules\pg-protocol\dist\index.js:8:42)
      at Socket.emit (events.js:322:22)
      at Socket.EventEmitter.emit (domain.js:482:12)
      at addChunk (_stream_readable.js:286:12)
      at readableAddChunk (_stream_readable.js:268:9)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '15',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c',
    line: '1379',
    routine: 'parserOpenTable',
    _length: 176,
    stackframes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
}
" 
I dont know how to create a table or schema. Can you help me on how to create one for this bot .

**Comment by AtoraSuunva** [comment]
The error is because you don't have the database setup

1. Create a database 
2. Create a database user and give them read/write permissions on the database you made in step 1
3. Run the script at https://github.com/AtlasTheBot/Booru-Discord/blob/master/sql/booru_settings.sql in the same database
4. Set the env vars `DB_HOST`, `DB_PORT`, `DB_USER`, `DB_PASSWORD`, `DB_DATABASE` in your dotenv to what you setup.

host is probably `localhost` in your setup, port is postgres default, user/password is from step 2, database is the name you gave it in step 1.
