### ISSUE TITLE
Postgres error

### ISSUE THREAD

**Issue by Xiu15** [AtoraSuunva/Booru-Discord#41]
I set up a database and run the script, but this error pops up when I try to run b!kc girl:

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
error: column "disablenextimage" of relation "booru_settings" does not exist
    at Parser.parseErrorMessage (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Logger Caught Uncaught Promise Error:
error: column "disablenextimage" of relation "booru_settings" does not exist
Stack:
error: column "disablenextimage" of relation "booru_settings" does not exist
    at Parser.parseErrorMessage (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Promise:
Promise {
  <rejected> error: column "disablenextimage" of relation "booru_settings" does not exist
      at Parser.parseErrorMessage (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
      at Parser.handlePacket (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\index.js:10:42)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at addChunk (_stream_readable.js:304:12)
      at readableAddChunk (_stream_readable.js:280:9)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '87',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_target.c',
    line: '1039',
    routine: 'checkInsertTargets',
    _length: 206,
    stackframes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
}

I don't know how to use postgre, help please...

**Comment by Xiu15** [comment]
ok, so looks like I fixed it by creating a column manually, but now I get this

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
error: value "693907657886793820" is out of range for type integer
    at Parser.parseErrorMessage (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Logger Caught Uncaught Promise Error:
error: value "693907657886793820" is out of range for type integer
Stack:
error: value "693907657886793820" is out of range for type integer
    at Parser.parseErrorMessage (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Promise:
Promise {
  <rejected> error: value "693907657886793820" is out of range for type integer
      at Parser.parseErrorMessage (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:278:15)
      at Parser.handlePacket (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\Users\OneDrive\Escritorio\Coding\Booru-Discord\node_modules\pg-protocol\dist\index.js:10:42)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at addChunk (_stream_readable.js:304:12)
      at readableAddChunk (_stream_readable.js:280:9)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    severity: 'ERROR',
    code: '22003',
    detail: undefined,
    hint: undefined,
    position: '113',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\numutils.c',
    line: '317',
    routine: 'pg_strtoint32',
    _length: 190,
    stackframes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
}

**Comment by Xiu15** [comment]
update: fixed it by changing the guild column's data type to bigint, but now when I run the command, I get "No images found."

**Comment by Xiu15** [comment]
do I need an API key or something?
gelbooru works fine, but danbooru and konachan give me "no images found"

**Comment by AtoraSuunva** [comment]
> error: column "disablenextimage" of relation "booru_settings" does not exist
> error: value "693907657886793820" is out of range for type integer

These were oversights on my part, I forgot to update the SQL create script after updating the table. Fixed in fecc7d67a146fd9f789e4d64493dc0fe9aae29ac.

> do I need an API key or something?
> gelbooru works fine, but danbooru and konachan give me "no images found"

None of the boorus require an API key (Some will limit the amount of tags you can use though, like Danbooru gives you a max of 2 tags to search with unless you pay)

I still manage to get a result from Danbooru and Konachan, are you trying to search using tags?

![image](https://user-images.githubusercontent.com/15206032/97378203-b7681480-18b9-11eb-9523-ed5cafc185f0.png)
